# Generated by Django 4.2.1 on 2023-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_files_remove_userquery_privious_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
