# Generated by Django 4.2.1 on 2023-06-06 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_files_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquery",
            name="file",
        ),
        migrations.AddField(
            model_name="userquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user_query",
            ),
        ),
    ]
